# Generated by Django 4.2.26 on 2025-11-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('JP', 'Japan'), ('CN', 'China'), ('BR', 'Brazil'), ('AE', 'United Arab Emirates'), ('SG', 'Singapore'), ('OT', 'Other')], default='IN', max_length=2, verbose_name='Country'),
        ),
    ]
