# Generated by Django 4.2.26 on 2025-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_upi_id',
            field=models.CharField(blank=True, help_text="Customer's VPA used for verification", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qr/'),
        ),
    ]
