# Generated by Django 4.2.26 on 2025-12-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_payer_upi_id_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provider Ref / UTR'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='PAYPAL', help_text='STRIPE, PAYPAL, etc.', max_length=50),
        ),
    ]
