# Generated by Django 4.2.26 on 2025-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_order_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('raw_body_text', models.TextField()),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_vpa', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_utr', models.CharField(blank=True, max_length=255, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
