# Generated by Django 4.2.26 on 2026-01-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('TIMED_OUT', 'Timed Out'), ('INCORRECT_AMOUNT', 'Incorrect Amount')], default='PENDING', max_length=20),
        ),
    ]
