# Generated by Django 4.2.26 on 2025-11-26 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(max_length=50, unique=True, verbose_name='Internal Code')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('display_name_en', models.CharField(max_length=100, null=True, verbose_name='Display Name')),
                ('display_name_es', models.CharField(max_length=100, null=True, verbose_name='Display Name')),
                ('display_name_de', models.CharField(max_length=100, null=True, verbose_name='Display Name')),
                ('display_name_fr', models.CharField(max_length=100, null=True, verbose_name='Display Name')),
                ('display_name_zh_hans', models.CharField(max_length=100, null=True, verbose_name='Display Name')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_name'],
            },
        ),
    ]
