# Generated by Django 4.2.26 on 2025-12-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Short summary for the card.'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='bi-book', help_text='Bootstrap icon class (e.g., bi-laptop)', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
