# Generated by Django 4.2.26 on 2025-12-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a 400x300px image for the card.', null=True, upload_to='categories/'),
        ),
    ]
