# Generated by Django 4.2.26 on 2025-11-26 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogContainsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Catalog Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Catalog Title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='Catalog Title')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='Catalog Title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Catalog Title')),
                ('title_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Catalog Title')),
                ('description', models.TextField(blank=True, verbose_name='Catalog Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Catalog Description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Catalog Description')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Catalog Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Catalog Description')),
                ('description_zh_hans', models.TextField(blank=True, null=True, verbose_name='Catalog Description')),
                ('catalog_code', models.CharField(help_text='Internal Code e.g. BUNDLE_2024', max_length=50, unique=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='thumbnails/catalogs/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_de', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_zh_hans', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(help_text='URL friendly name', max_length=255, unique=True)),
                ('item_type', models.CharField(choices=[('MOCK_TEST', 'Mock Test'), ('WORKSHOP', 'Workshop'), ('VIDEO_COURSE', 'Video Course'), ('NOTE', 'Note')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='thumbnails/items/')),
                ('is_active', models.BooleanField(default=False, help_text='Is this item listed for sale?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('text', models.TextField(verbose_name='Review Text')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='marketplace.marketplaceitem')),
            ],
        ),
    ]
