# Generated by Django 4.2.26 on 2025-11-26 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='items', to='core.category'),
        ),
        migrations.AddField(
            model_name='marketplacecatalog',
            name='items',
            field=models.ManyToManyField(related_name='catalogs', through='marketplace.CatalogContainsItem', to='marketplace.marketplaceitem'),
        ),
        migrations.AddField(
            model_name='catalogcontainsitem',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplacecatalog'),
        ),
        migrations.AddField(
            model_name='catalogcontainsitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceitem'),
        ),
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together={('item', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogcontainsitem',
            unique_together={('catalog', 'item')},
        ),
    ]
