# Generated by Django 4.2.26 on 2025-12-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='base_enrollment_count',
            field=models.IntegerField(default=0, help_text='Starting number to show for social proof (e.g. 1500)'),
        ),
    ]
