# Generated by Django 4.2.26 on 2025-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplaceitem_base_enrollment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='country',
            field=models.CharField(default='India', help_text="Reviewer's Country", max_length=100),
        ),
    ]
