# Generated by Django 4.2.26 on 2025-12-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_testimonial_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for users outside India', max_digits=10, verbose_name='Price (USD)'),
        ),
    ]
