# Generated by Django 4.2.26 on 2026-01-09 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0005_marketplaceitem_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='Does completing this provide a certificate?'),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='The creator/instructor of this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplaceitem',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Show Bestseller badge?'),
        ),
    ]
