# Generated by Django 4.2.26 on 2026-01-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_marketplaceitem_has_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitem',
            name='item_type',
            field=models.CharField(choices=[('MOCK_TEST', 'Mock Test'), ('WORKSHOP', 'Workshop'), ('VIDEO_COURSE', 'Video Course'), ('TEXT_COURSE', 'Text Course'), ('NOTE', 'Note')], max_length=20),
        ),
    ]
