# Generated by Django 4.2.26 on 2026-01-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_marketplaceitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceitem',
            name='item_type',
            field=models.CharField(choices=[('MOCK_TEST', 'Mock Test'), ('SCHOLARSHIP_TEST', 'Scholarship Test'), ('WORKSHOP', 'Workshop'), ('VIDEO_COURSE', 'Video Course'), ('TEXT_COURSE', 'Text Course'), ('NOTE', 'Note')], max_length=20),
        ),
    ]
