# Generated by Django 4.2.26 on 2025-11-26 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopAttributes',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workshop_details', serialize=False, to='marketplace.marketplaceitem')),
                ('description_long', models.TextField(help_text='Full schedule or curriculum details', verbose_name='Detailed Agenda')),
                ('description_long_en', models.TextField(help_text='Full schedule or curriculum details', null=True, verbose_name='Detailed Agenda')),
                ('description_long_es', models.TextField(help_text='Full schedule or curriculum details', null=True, verbose_name='Detailed Agenda')),
                ('description_long_de', models.TextField(help_text='Full schedule or curriculum details', null=True, verbose_name='Detailed Agenda')),
                ('description_long_fr', models.TextField(help_text='Full schedule or curriculum details', null=True, verbose_name='Detailed Agenda')),
                ('description_long_zh_hans', models.TextField(help_text='Full schedule or curriculum details', null=True, verbose_name='Detailed Agenda')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prerequisites')),
                ('prerequisites_en', models.TextField(blank=True, null=True, verbose_name='Prerequisites')),
                ('prerequisites_es', models.TextField(blank=True, null=True, verbose_name='Prerequisites')),
                ('prerequisites_de', models.TextField(blank=True, null=True, verbose_name='Prerequisites')),
                ('prerequisites_fr', models.TextField(blank=True, null=True, verbose_name='Prerequisites')),
                ('prerequisites_zh_hans', models.TextField(blank=True, null=True, verbose_name='Prerequisites')),
                ('total_duration_hours', models.DecimalField(decimal_places=2, help_text='Approximate total duration', max_digits=4)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_workshops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkshopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('max_capacity', models.PositiveIntegerField(default=50)),
                ('current_enrolled_count', models.PositiveIntegerField(default=0, help_text='Auto-updated by signals/logic')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Zoom/Meet Link')),
                ('recording_link', models.URLField(blank=True, help_text='Available after session ends', verbose_name='Recording URL')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workshops.workshopattributes')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attended', models.BooleanField(default=False, help_text='Did the user actually show up?')),
                ('feedback_submitted', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='workshops.workshopsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
    ]
