# Generated by Django 4.2.26 on 2026-01-10 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0006_marketplaceitem_has_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttributes',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='course_details', serialize=False, to='marketplace.marketplaceitem')),
                ('course_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=50)),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements/Prerequisites')),
                ('what_you_will_learn', models.TextField(blank=True, verbose_name='What you will learn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Module Title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.courseattributes')),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Lesson Title')),
                ('video_url', models.URLField(blank=True, help_text='Embed URL for YouTube/Vimeo (e.g. https://www.youtube.com/embed/VIDEO_ID)', verbose_name='Video URL')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Length in minutes')),
                ('rich_text_content', models.TextField(blank=True, verbose_name='Notes / Description')),
                ('is_preview', models.BooleanField(default=False, help_text='Allow users to watch this without purchasing?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule')),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
    ]
