# Generated by Django 4.2.26 on 2025-11-26 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestAttributes',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mock_test_details', serialize=False, to='marketplace.marketplaceitem')),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Total time allowed in minutes')),
                ('pass_percentage', models.PositiveIntegerField(default=50, help_text='Minimum % to pass')),
                ('has_negative_marking', models.BooleanField(default=False)),
                ('negative_marking_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. 0.25 for 25% deduction', max_digits=5)),
                ('ranking_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for the global ranking (e.g., 1.5 for final exams)', max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted')], default='IN_PROGRESS', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mocktests.mocktestattributes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRankMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_xp', models.IntegerField(db_index=True, default=0)),
                ('tests_taken_count', models.PositiveIntegerField(default=0)),
                ('avg_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Section Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Section Title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='Section Title')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='Section Title')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Section Title')),
                ('title_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Section Title')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mocktests.mocktestattributes')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('question_text_en', models.TextField(null=True, verbose_name='Question Text')),
                ('question_text_es', models.TextField(null=True, verbose_name='Question Text')),
                ('question_text_de', models.TextField(null=True, verbose_name='Question Text')),
                ('question_text_fr', models.TextField(null=True, verbose_name='Question Text')),
                ('question_text_zh_hans', models.TextField(null=True, verbose_name='Question Text')),
                ('explanation', models.TextField(blank=True, help_text='Shown after the test is submitted', verbose_name='Explanation')),
                ('explanation_en', models.TextField(blank=True, help_text='Shown after the test is submitted', null=True, verbose_name='Explanation')),
                ('explanation_es', models.TextField(blank=True, help_text='Shown after the test is submitted', null=True, verbose_name='Explanation')),
                ('explanation_de', models.TextField(blank=True, help_text='Shown after the test is submitted', null=True, verbose_name='Explanation')),
                ('explanation_fr', models.TextField(blank=True, help_text='Shown after the test is submitted', null=True, verbose_name='Explanation')),
                ('explanation_zh_hans', models.TextField(blank=True, help_text='Shown after the test is submitted', null=True, verbose_name='Explanation')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('NUMERIC', 'Numeric Input')], default='MCQ', max_length=20)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktests.testsection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500, verbose_name='Option Text')),
                ('option_text_en', models.CharField(max_length=500, null=True, verbose_name='Option Text')),
                ('option_text_es', models.CharField(max_length=500, null=True, verbose_name='Option Text')),
                ('option_text_de', models.CharField(max_length=500, null=True, verbose_name='Option Text')),
                ('option_text_fr', models.CharField(max_length=500, null=True, verbose_name='Option Text')),
                ('option_text_zh_hans', models.CharField(max_length=500, null=True, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mocktests.testquestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('numeric_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mocktests.usertestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktests.testquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mocktests.questionoption')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
