# Generated by Django 4.2.26 on 2025-11-26 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='audio_clip',
            field=models.FileField(blank=True, help_text='For IELTS/TOEFL Listening', null=True, upload_to='questions/audio/'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Diagrams for JEE/NEET', null=True, upload_to='questions/images/'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='score_awarded',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='For Essay or Subjective questions', null=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='explanation_de',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='explanation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='explanation_es',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='explanation_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='explanation_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('NUMERIC', 'Numeric Input'), ('ESSAY', 'Essay / Long Answer')], default='MCQ', max_length=20),
        ),
        migrations.CreateModel(
            name='ComprehensionPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Passage Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='passages/images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='mocktests.testsection')),
            ],
        ),
        migrations.AddField(
            model_name='testquestion',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='mocktests.comprehensionpassage'),
        ),
    ]
