# Generated by Django 4.2.26 on 2025-11-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0003_questionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='audio_clip',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='question_image',
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='questions/images/')),
                ('caption', models.CharField(blank=True, help_text='Optional description', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mocktests.testquestion')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='questions/audio/')),
                ('label', models.CharField(blank=True, help_text="e.g., 'Speaker 1', 'Conversation A'", max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='mocktests.testquestion')),
            ],
        ),
    ]
