# Generated by Django 4.2.26 on 2025-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0004_remove_testquestion_audio_clip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/images/'),
        ),
    ]
