# Generated by Django 4.2.26 on 2025-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0005_questionoption_option_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_marked_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
