# Generated by Django 4.2.26 on 2025-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0006_useranswer_is_marked_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestattributes',
            name='instructions',
            field=models.TextField(blank=True, default='<ol>\n        <li>Total duration of this examination is defined in the timer.</li>\n        <li>The clock will be set at the server. The countdown timer in the top right corner of screen will display the remaining time available for you to complete the examination.</li>\n        <li>The question palette displayed on the right side of screen will show the status of each question.</li>\n        <li>You can mark a question for review to revisit it later.</li>\n        <li><strong>Marking Scheme:</strong> Correct Answer: +1, Incorrect Answer: 0.</li>\n        </ol>', help_text='Specific rules for this exam (e.g., Marking scheme, allowed items).', verbose_name='Instructions'),
        ),
    ]
