# Generated by Django 4.2.26 on 2025-12-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0007_mocktestattributes_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='testsection',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testsection',
            name='section_duration',
            field=models.IntegerField(help_text='Time limit for this section in minutes', null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='audio_answer',
            field=models.FileField(blank=True, null=True, upload_to='answers/audio/'),
        ),
    ]
