# Generated by Django 4.2.26 on 2025-12-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0008_testquestion_difficulty_testsection_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestattributes',
            name='exam_type',
            field=models.CharField(choices=[('GENERAL', 'General Mock Test'), ('SAT', 'Digital SAT (Adaptive)'), ('IELTS', 'IELTS Academic/General'), ('JEE_MAINS', 'JEE Mains'), ('JEE_ADVANCED', 'JEE Advanced')], default='GENERAL', max_length=20),
        ),
    ]
