# Generated by Django 4.2.26 on 2025-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0009_mocktestattributes_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktestattributes',
            name='exam_type',
            field=models.CharField(choices=[('GENERAL', 'General Mock Test'), ('SAT_ADAPTIVE', 'Digital SAT (Adaptive)'), ('SAT_NON_ADAPTIVE', 'Digital SAT (Non-Adaptive)'), ('IELTS', 'IELTS Academic/General'), ('JEE_MAINS', 'JEE Mains'), ('JEE_ADVANCED', 'JEE Advanced')], default='GENERAL', max_length=20),
        ),
    ]
