# Generated by Django 4.2.26 on 2025-12-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0010_alter_mocktestattributes_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer_value',
            field=models.CharField(blank=True, help_text='For Numeric/Input questions. Enter the exact correct value.', max_length=255, null=True, verbose_name='Correct Answer (Input)'),
        ),
    ]
