# Generated by Django 4.2.26 on 2026-01-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0011_testquestion_correct_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktestattributes',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='When this test closes', null=True),
        ),
        migrations.AddField(
            model_name='mocktestattributes',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='When this test opens', null=True),
        ),
    ]
