# Generated by Django 4.2.26 on 2026-01-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocktests', '0012_mocktestattributes_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Syllabus')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='mocktests.mocktestattributes')),
            ],
        ),
        migrations.CreateModel(
            name='TestEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Eligibility')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='mocktests.mocktestattributes')),
            ],
        ),
    ]
